### ISSUE TITLE
Config files get overwritten

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/LDWizard-ErfgoedWizard#11]
Suggestion for generating unique names for convert.ts and rules.rml.ttl to prevent overwriting them when doing an automatic upload to the data platform.

**Comment by GerwinBosch** [comment]
@EnnoMeijers They should still be available as previous versions, or would you want to include original file-name to be part of the filename?

**Comment by EnnoMeijers** [comment]
Yes, when converting multiple source files the version trail of convert.ts is confusing, including the original file-name would improve this!

**Comment by wouterbeek** [comment]
I agree with this, you would have the best of both worlds:
- Uploading the result of transforming `cities.csv` and `organisations.csv` would result in distinguishable transformation files `cities.rml.ttl` and `organisations.rml.ttl`, and
- Performing these transformations multiple times would be stored as versions of these distinguishable files.
