### ISSUE TITLE
Generate IRI based on numeric field

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/LDWizard-ErfgoedWizard#13]
Suggestion to add functionality to generate a URI (not the key) based on an numeric field using a simple template?

**Comment by wouterbeek** [comment]
@EnnoMeijers Do you mean something like the following:

A column-level configuration where the user specifies one IRI `{prefix}` such that the `{value}` in individual cells from that column result in object term IRIs of the form `{prefix}{uri_encoded(value)}`.

This may include non-numeric cell values too.  (E.g., value `0123` may be treated as a string, subsequently not omitting the zero from the IRI).

**Comment by EnnoMeijers** [comment]
This is indeed what I had in mind or actually better ;)

**Comment by rlzijdeman** [comment]
@wouterbeek to me #13 reads like the option to specify value-types (e.g. xsd:integer, xsd:date) for a column in the object position. 

A restricted version of #15 would be to declare the rdf:type for non-keyed columns in the subject position.
