### ISSUE TITLE
Questions about the README file

### ISSUE THREAD

**Issue by wouterbeek** [netwerk-digitaal-erfgoed/LDWizard-ErfgoedWizard#14]
# 1

I would like to clarify the following texts in the README:

```
## Production docker deployment
```

^ What does this mean?  Step 3 will run an application on localhost.  Why is that a production deployment?

# 2

```
1. Build the image:

2. Start the service:
```

^ Is this a service that runs/interprets images?

# 3

```
To mark a version as stable, run yarn run `util:markStable`.
```

^ What does it mean to mark a version as stable?  When is this typically done?  Is it a requirement for the production deployment, or the other way round?

**Comment by GerwinBosch** [comment]
1. This produced Image is (will be) used to host a production instance, it could also be used to test the Wizard without having to install the prerequisites (except for docker)
    - Fixed by adding some text and removing "production" from the header
2. The service will "serve" an instance of the Wizard
3. That one was still a leftover from our template.
