### ISSUE TITLE
Detect datatypes of columns

### ISSUE THREAD

**Issue by GerwinBosch** [netwerk-digitaal-erfgoed/LDWizard-ErfgoedWizard#18]
## Use case

As a user, I want the potential datatype IRIs for columns to be detected for me.

- As a user, I may not be aware of which datatype IRIs are possible.
- As a user, I may want to save time by using the suggested defaults.

## To discuss

- What happens if there are multiple "correct" datatype IRIs?

## To implement

- [ ] Set the most fitting datatype IRI as the per-column default.

## Blocked by

pldn/LDWizard#10

**Comment by wouterbeek** [comment]
Continued in <https://github.com/netwerk-digitaal-erfgoed/LDWizard/issues/34>.
