### ISSUE TITLE
Good default for subject term IRIs

### ISSUE THREAD

**Issue by wouterbeek** [netwerk-digitaal-erfgoed/LDWizard-ErfgoedWizard#21]
# Observation

When the user sets a base IRI and key column, subject term IRIs are created according to these settings.

When no key column is specified, the default is currently to use the row number in the table.

When the user did not select a key column and also did not specify a base IRI, this could result in different datasets with the same subject IRI (i.e., `{base-iri}{row-number}`).

# Suggestion

It may be better to not use the row number for creating the subject IRIs, and instead use a local name that is unique for each content row (either a hash for that row or a UUID).

```
{base}/def/{Class}
{base}/def/{property}
{base}/id/{referentie}
```

1. `{base}` is the base IRI that is either:
    a. explicitly set by the Domain Expert in the LD Wizard GUI,
    b. or that is based on the default value configured by the Developer.
2. If the Developer configures the base IRI prefix to be `https://data.netwerkdigitaalerfgoed.nl/` then the base IRI in the LD Wizard interface becomes `https://data.netwerkdigitaalerfgoed.nl/{hash}/`, for a specific hash.  `{hash}` is based on the contents of the CSV input file. This can be calculated as a by-product of reading the CSV file, which is necessary anyway.
3. *Classes* and *properties* that are relative IRIs use the IRI prefix `{base}/def/`.  *Instances* that are relative IRIs use the IRI prefix `{base}/id/`.
4. The forward slashes (`/`) are only added between IRI components if this does not result in consecutive slashes.
5. If the Domain Expert chooses to let `{base}` end in a hash character (`#`), or if the Developer chooses to let the configured base IRI prefix end in a hash character (`#`), then this hash character is replaced by a forward slash character (`/`), and the last forward slash character is replaced by a hash character.

### Example

Suppose the Domain Expert uploads the following table and configures nothing:

| **naam** | **ID** |
|---------|-------|
| Ivo     | 123 |

```ttl
<https://data.netwerkdigitaalerfgoed.nl/382138209/id/123> a <https://data.netwerkdigitaalerfgoed.nl/382138209/def/Person>;
  <https://data.netwerkdigitaalerfgoed.nl/382138209/def/naam> "Ivo".
```

Suppose the Developer chooses to let the base IRI prefix end in a hash character (e.g., `https://example.com#`):

```ttl
<https://example.com/382138209/id#123> a <https://example.com/382138209/def#Person>;
  <https://example.com/382138209/def#naam> "Ivo".
```

**Comment by ivozandhuis** [comment]
@wouterbeek I think you and I created a fairly cleaver idea, with the hash per dataset somewhere in the base IRI. You made a note of that?

**Comment by wouterbeek** [comment]
@ivozandhuis Indeed!  I have updated the main description accordingly.
