### ISSUE TITLE
Add support for excel files

### ISSUE THREAD

**Issue by GerwinBosch** [netwerk-digitaal-erfgoed/LDWizard-ErfgoedWizard#22]
## User story

As a user, I want to be able to upload a `.xlsx` file in order to make it easier to transform new datasets.

## To implement

- [ ] Transform a `.xlsx` file to a matrix in the config step and  extract the meta-information
- [ ] Only use the first tab as data

## Workaround

Load and export the `.xlsx` as CSV

**Comment by wouterbeek** [comment]
Continue this over at: <https://github.com/netwerk-digitaal-erfgoed/LDWizard/issues/13>
