### ISSUE TITLE
Allow selecting a CSV from a URL

### ISSUE THREAD

**Issue by GerwinBosch** [netwerk-digitaal-erfgoed/LDWizard-ErfgoedWizard#23]
## User story

As a user, I want to be able to enter a URL to select a CSV to transform in order to no longer download the CSV

## To implement

- [ ] Add a text field where the user is able to enter a URL and use it to load the CSV
- [ ] Communicate to the users that it will still download the CSV to the local machine

## Workaround

Download the CSV first

**Comment by wouterbeek** [comment]
Continue this in <https://github.com/netwerk-digitaal-erfgoed/LDWizard/issues/38>.
