### ISSUE TITLE
Deploy an instance of the ErfgoedWizard

### ISSUE THREAD

**Issue by GerwinBosch** [netwerk-digitaal-erfgoed/LDWizard-ErfgoedWizard#24]
# Task

We want to deploy an instance of the ErfgoedWizard.

It would be nice to automatically deploy the master branch to this instance

**Comment by ddeboer** [comment]
See https://github.com/netwerk-digitaal-erfgoed/bruikbaar/issues/32 (private repo) for our generic hosting approach, which includes automatic deployments from master (in a Docker container) to a Kubernetes cluster. The Network of Terms [will be the first app](https://github.com/netwerk-digitaal-erfgoed/network-of-terms-comunica/pull/25) to adopt that approach. If everything works fine, we can deploy the LDWizard the same way.
