### ISSUE TITLE
Add Nginx rewrite rule

### ISSUE THREAD

**Issue by ddeboer** [netwerk-digitaal-erfgoed/LDWizard-ErfgoedWizard#28]
The app redirects from https://ldwizard.netwerkdigitaalerfgoed.nl/ to https://ldwizard.netwerkdigitaalerfgoed.nl/1, but refreshing the https://ldwizard.netwerkdigitaalerfgoed.nl/1 doesn’t work.

This is due to the fact that Nginx config in Docker doesn’t rewrite URLs to `/`.

**Comment by GerwinBosch** [comment]
@ddeboer do you have more reproduction steps? When following your description I was unable to reproduce it. (I did see this issue on the "previous deployment" however)

![refresh](https://user-images.githubusercontent.com/7578412/94123903-a6f4f200-fe54-11ea-82a7-5295cdd6fd8d.gif)

**Comment by ddeboer** [comment]
Sorry, red herring (browser cache?). On the new infrastructure requests to `https://ldwizard.netwerkdigitaalerfgoed.nl/*` land at the app correctly.

**Comment by GerwinBosch** [comment]
Reopened this issue as it happens now in the latest version
