### ISSUE TITLE
Value of key column is not used to generate IRIs

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/LDWizard-ErfgoedWizard#31]
By selecting a unique key column I would expect the value of the key column to be part of the generated IRI for the resource. This is not the case, the wizard generates new identifiers like: <base_uri>/id/0, <base_uri>/id/1,... 
If I am right a prevision version of the wizard generated <base_uri>/<value_of_id_column>. Is this changed on purpose?

**Comment by wouterbeek** [comment]
@EnnoMeijers That sounds like a bug to me...  Can you specify the steps to reproduce this?  When I select a key column I receive IRIs of the form `{prefix}/{hash}/id/{value}`, where `{value}` is the content of cells in the selected key column.

**Comment by EnnoMeijers** [comment]
See the attached csv and the nt result file. The 'Id' column was selected as key column. 
[testdata.zip](https://github.com/netwerk-digitaal-erfgoed/LDWizard-ErfgoedWizard/files/5290941/testdata.zip)

**Comment by wouterbeek** [comment]
Thanks, one less bug in LD Wizard ;-)
