### ISSUE TITLE
'dev' is added to base_IRI for unmapped column

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/LDWizard-ErfgoedWizard#32]
Columns that are not mapped to a specific property are created with an extra '/dev/' in the IRI, like: <https://data.netwerkdigitaalerfgoed.nl/denbosch/bevolkingsregister/1822/dev/Wijk>

I would expect just the base_IRI with the column name added, if I am right this worked like this in previous version. What is the reason for changing this?

**Comment by wouterbeek** [comment]
This is because of #21, where we introduce the distinction between definition IRIs and instance IRIs.  `dev/` is probably a typo and should be `def/`.  Instance IRIs are now suffixed with `id/`.

**Comment by wouterbeek** [comment]
I fixed this in the meantime!
