### ISSUE TITLE
LDWizard no longer compatible to CoW

### ISSUE THREAD

**Issue by rlzijdeman** [netwerk-digitaal-erfgoed/LDWizard-ErfgoedWizard#35]
Hi, once done converting the dataset in LDWizard one can download a CoW script to redo the conversion in CoW.

The cow script actually no longer functions in the sense that one can run the CoW script but it creates no triples. The feedback from the terminal is: 

```
KeyError: 'NAAM'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/cow_csvw/converter/csvw.py", line 614, in process
    value = row[csvw_name]
```

**Comment by GerwinBosch** [comment]
@rlzijdeman I think this has been fixed in the meantime. If it still occurs, could you share the headers? (Or specifically which header causes an issue)

**Comment by rlzijdeman** [comment]
affirmative. works again, thank you for fixing it @GerwinBosch
