### ISSUE TITLE
Adding an additional vocabulary to the sparql service is not being picked up

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/LDWizard-ErfgoedWizard#36]
I added the PNV vocabulary to the https://data.netwerkdigitaalerfgoed.nl/ld-wizard/sdo dataset and rebuild the LDWizard-ErfgoedWizard with the default config but the properties from the PNV vocabulary do not show up in the UI.

**Comment by wouterbeek** [comment]
Thanks for reporting!  The SPARQL query for matching properties is not generic enough (it probes for RDF but not OWL type assertions).  I have added support for this in <https://github.com/netwerk-digitaal-erfgoed/LDWizard-Core/pull/6>.
