### ISSUE TITLE
Autocomplete ignores prefix

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/LDWizard-ErfgoedWizard#5]
In the 'choose property' dialogue the autocomplete ignore the namespace prefix (like 'sdo') which leads to unexpected behavior when typing 'sdo:au...'. In general the autocomplete lacks transparency in showing the results.

**Comment by wouterbeek** [comment]
It would indeed be nice if prefixes defined in the used dataset/endpoint can also be used in the LD Wizard GUI.
