### ISSUE TITLE
Close 'choose property dialogue' with <enter>

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/LDWizard-ErfgoedWizard#9]
Suggestion to make the 'choose property' dialogue close on <enter> in stead of forcing the user to use <confirm>.

**Comment by wouterbeek** [comment]
@EnnoMeijers Do you mean that is the following dialog selecting an IRI would close the dialog.  Would the "Confirm" button even be needed in that case?  For the current situation I agree: users would almost always click on "Confirm" after selecting an IRI.  However, we may want to ended this dialog in the future, e.g., allowing a datatype IRI or language tag to be set.

![Screenshot from 2020-08-25 19-00-12](https://user-images.githubusercontent.com/1685012/91206614-b96df580-e707-11ea-9a2d-ca7f0967d009.png)

Or do you mean that the `Enter` key should be bound to the "Confirm" button (and the button should stay)?  In that regard: I also notice that the `Esc` key is bound to the "Cancel" button, but has to be pressed twice ATM.

**Comment by EnnoMeijers** [comment]
I was referring to the first case indeed, but I agree that this might not be the right approach when the dialogue is extended. Binding the <Enter> to the "Confirm" makes also sense. But maybe review this topic as part of a general usability review at a later moment.

**Comment by wouterbeek** [comment]
@GerwinBosch Do you agree with binding the `Enter` button to the "Confirm" button, and binding the (single-press) `Esc` key to the "Cancel" button?  (Maybe also for other dialogs with a similar Y/N button pair.)
